#!/usr/bin/env python
import sys
import requests
import datetime
import jpholiday
from urllib.request import urlopen
from bs4 import BeautifulSoup
from linebot import LineBotApi
from linebot.v3.messaging import Configuration, ApiClient, MessagingApi, PushMessageRequest, TextMessage

from settings import config

# 土日祭日は実行しない
today = datetime.date.today()
if (today.weekday() >= 5) \
    or (today.month == 12 and today.day == 31) \
    or (today.month == 1 and (today.day >= 1 and today.day <= 3)) \
    or (jpholiday.is_holiday(today) == True):
    sys.exit()

# 日経平均スクレイピング
html = urlopen('https://db.225225.jp/bp1.php')
soup = BeautifulSoup(html , "html.parser")

nikkei_tit = soup.find_all('div' , class_ = 'if_tit')
nikkei_cur = soup.find_all('div' , class_ = 'if_cur')
nikkei_per = soup.find_all('div' , class_ = 'per')
nikkei_day = soup.find_all('div' , class_ = 'if_day')

# メッセージ形成
notification_message = '\n'
for i in range(len(nikkei_tit)):
    notification_message = notification_message + '\t'.join( [nikkei_tit[i].string, nikkei_cur[i].string, nikkei_per[i].string, nikkei_day[i].string] ) + '\n'

# line通知
if config.LINE_NOTIFY:
    line_notify_token = config.TOKEN
    line_notify_api = 'https://notify-api.line.me/api/notify'
    headers = {'Authorization': f'Bearer {line_notify_token}'}
    data = {'message': f'{notification_message}'}
    requests.post(line_notify_api, headers = headers, data = data)

# line messaging api
if config.LINE_MESSAGING_API:
    CHANNEL_ACCESS_TOKEN = config.CHANNEL_ACCESS_TOKEN
    USER_ID = config.USER_ID

    configuration = Configuration(access_token=CHANNEL_ACCESS_TOKEN)
    with ApiClient(configuration) as api_client:
        messaging_api = MessagingApi(api_client)
        message = TextMessage(text=notification_message)
        push_message_request = PushMessageRequest(to=USER_ID, messages=[message])
        messaging_api.push_message(push_message_request)
