#!/usr/bin/env python
import sys
import requests
import datetime
import jpholiday
from urllib.request import urlopen
from bs4 import BeautifulSoup

from settings import config

# 土日祭日は実行しない
today = datetime.date.today()
if (today.weekday() >= 5) or (jpholiday.is_holiday(today) == True):
    sys.exit()

# 日経平均スクレイピング
html = urlopen('https://db.225225.jp/bp1.php')
soup = BeautifulSoup(html , "html.parser")

nikkei_tit = soup.find_all('div' , class_ = 'if_tit')
nikkei_cur = soup.find_all('div' , class_ = 'if_cur')
nikkei_per = soup.find_all('div' , class_ = 'per')
nikkei_day = soup.find_all('div' , class_ = 'if_day')

# メッセージ形成
notification_message = '\n'
for i in range(len(nikkei_tit)):
    notification_message = notification_message + '\t'.join( [nikkei_tit[i].string, nikkei_cur[i].string, nikkei_per[i].string, nikkei_day[i].string] ) + '\n'

# line通知
line_notify_token = config.TOKEN
line_notify_api = 'https://notify-api.line.me/api/notify'
headers = {'Authorization': f'Bearer {line_notify_token}'}
data = {'message': f'{notification_message}'}
requests.post(line_notify_api, headers = headers, data = data)
